name: CI Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, windows-2019]
        php: ["7.3", "7.4", "8.0"]
    name: Run CI PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}
      - run: php -v

      - name: Run CI
        run: |
          composer validate
          php test.php
