name: CI Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ["7.3", "7.4", "8.0"]
    name: Run CI PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug #optional
          extensions: memcached
      - run: php -v

      - name: Run CI
        run: |
          composer validate
          php test.php
